FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# Dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/api.py ./api.py

ENV MODEL_PATH=/mnt/model/model.pkl \
    VERSION=0.1.0 \
    FLASK_APP=api.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=50023"]